CREATE TABLE `test`.`new_table` (
  `ID` INT(8) NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(25) NOT NULL,
  `AGE` INT NOT NULL,
  `ISADMIN` VARCHAR(45) BINARY NOT NULL,
  `CREATEDDATE` DATE NOT NULL,
  PRIMARY KEY (`ID`));
